spring:
  profiles:
    active: db, db_@profileActive@, core, core_@profileActive@, admin, admin_@profileActive@
  message:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  ERROR
