spring:
  profiles:
    active: db, db_@profileActive@, core, core_@profileActive@, admin, admin_@profileActive@ wx, wx_@profileActive@
  message:
    encoding: UTF-8

server:
  port: 8090

logging:
  config: classpath:logback-spring.xml