spring:
  profiles:
    active: db, db_@profileActive@, core, core_@profileActive@, admin, admin_@profileActive@ wx, wx_@profileActive@
  message:
    encoding: UTF-8

server:
  port: 8090

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  ERROR
    org.linlinjava.litemall.db:  ERROR
    org.linlinjava.litemall.admin:  ERROR
    org.linlinjava.litemall.wx:  ERROR
    org.linlinjava.litemall:  ERROR
