spring:
  datasource:
    druid:
      url:  jdbc:mysql://mysql57:3306/litemall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username:  litemall
      password:  litemall123456
